version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./backend/database.sqlite:/app/database.sqlite
      - ./backend/images:/app/images
    environment:
      - NODE_ENV=development
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
